(require 'clpy)

(py:initialize)

(sb-int:with-float-traps-masked (:divide-by-zero :invalid :overflow)
  (defparameter *numpy* (py:import "numpy")))

(py:import-as (("matplotlib.pyplot" ((plot  "plot")
				     (xlabel "xlabel")
				     (ylabel "ylabel")
				     (title "title")
				     (legend "legend")
				     (show "show"))))
  (py:let ((x (py:new '(:list 1 2 3 4 5)))
	   (y (py:new '(:list 2 4 6 8 10))))
    (py:call plot :args (list x y) :kwargs '(("label" . "y = 2x")
					     ("color" . "blue")
					     ("marker" . "o")))
    (py:call xlabel :args (list "X-axis"))
    (py:call ylabel :args (list "Y-axis"))
    (py:call title :args (list "Simple Line Plot"))
    (py:call legend)
    (py:call show)))

;; (py:import-as (("matplotlib" ((plt "pyplot"))))
;;   (py:let ((x (py:new '(:list 1 2 3 4 5)))
;; 	   (y (py:new '(:list 2 4 6 8 10))))
;;     (py:let ((plot (py:get-attr plt "plot"))
;; 	     (xlabel (py:get-attr plt "xlabel"))
;; 	     (ylabel (py:get-attr plt "ylabel"))
;; 	     (title (py:get-attr plt "title"))
;; 	     (legend (py:get-attr plt "legend"))
;; 	     (show (py:get-attr plt "show")))
;;       (py:call plot :args (list x y) :kwargs '(("label" . "y = 2x")
;; 					       ("color" . "blue")
;; 					       ("marker" . "o")))
;;       (py:call xlabel :args (list "X-axis"))
;;       (py:call ylabel :args (list "Y-axis"))
;;       (py:call title :args (list "Simple Line Plot"))
;;       (py:call legend)
;;       (py:call show))))

(py:dec-xref *numpy*)

(py:finalize)
