(defpackage :clpy.slice
  (:nicknames :py.slice)
  (:use :cl :plus-c)
  (:shadow #:step)
  (:export #:p
           #:new
           #:unpack
           #:adjust
           #:pack))

(in-package :clpy.slice)

(clpy.type:define-type "PySlice_Type" slice)

(defun p (o)
  (clpy.type:of o :slice))

(defun new (start stop step)
  (clpy.util:ensure-null-as-nil
      (py:let ((-start (py:new start))
               (-stop (py:new stop))
               (-step (py:new step)))
        (clpy.ffi.fns:py-slice-new -start -stop -step))
    (error 'py.exc:generic-error)))

(defun unpack (o)
  "Return the start, the stop and the step of a slice object. The returned values can be pass to ADJUST."
  (c-let ((start clpy.ffi:py-ssize-t)
           (stop clpy.ffi:py-ssize-t)
           (step clpy.ffi:py-ssize-t))
    (clpy.util:ensure-zero
        (clpy.ffi.fns:py-slice-unpack o (start &) (stop &) (step &))
      (error 'py.exc:generic-error))
    (values start stop step)))

(defun adjust (len start stop step)
  "Adjust the start and stop of the slices assuming the length is LEN. START, STOP and STEP can be generated from UNPACK."
  (clpy.util:ensure-zero
      (c-let ((-start clpy.ffi:py-ssize-t :from start)
              (-stop clpy.ffi:py-ssize-t :from stop)
              (-step clpy.ffi:py-ssize-t :from step))
        (clpy.ffi.fns:py-slice-adjust-indices len (-start &) (-stop &) (-step &)))
    (error 'py.exc:generic-error))
  (values start stop step))

(defun pack (start stop step)
  "Free the memory pointer generated by UNPACK."
  (autowrap:free start)
  (autowrap:free stop)
  (autowrap:free step))
    
(clpy.type:define-type "PyEllipsis_Type" ellipsis)
